# 构建项目并部署到 GitHub Pages
name: Deploy Site to Pages

# 触发条件
on:
  # 推送到 main 分支时触发
  push:
    branches: [main]

  # 允许在 Actions 选项卡中手动运行此工作流
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限, 以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许一个并发部署
# 不取消正在进行的作业
concurrency:
  group: pages
  cancel-in-progress: false

# 工作流任务
jobs:
  # 构建任务
  build:
    # 运行平台
    runs-on: ubuntu-latest
    # 执行步骤
    steps:
      # 检出代码
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 设置 PNPM
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10

      # 设置 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      # 配置 GitHub Pages
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      # 安装依赖
      - name: Install Dependencies
        run: pnpm install

      # 构建项目
      - name: Build Project
        run: pnpm build-only

      # 上传构建产物
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  # 部署任务
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
